#ifndef VBA_GLSL_SRC_H
#define VBA_GLSL_SRC_H

#include "swooshboy.h"

/* glslSrc
 * glsl source container object
 *
 * glsl source files are included in VBA as const unsigned char[] variables
 * generated by cmake. This class just makes handling them a little easier.
 *
 * This seemed like the most sensible way to do this, as the same glsl source
 * file can contain multiple glsl shaders, and can be reused. Thanks to the way
 * glShaderSource() handles these variables, we can prepend preprocessor
 * directives without modifying the glsl source variable.
 *
 *
 * Still needs copy constructor
 * Still needs assignment operator
 */
class glslSrc {
    friend class glslShader;
    friend class vbaGL;
public:
    glslSrc(); //dummy constructor
    // Constructor sets source pointer and length
    glslSrc(char *src_in, const uint len);
    bool init(char *src_in, const uint len);
    ~glslSrc();

protected:
    bool is_init;
    // The glsl source
    char *src_main;
    // Length of the array
    uint src_main_len;
};
#define CREATE_GLSL_SRC_OBJ(obj, shd) \
    DECLARE_RES(glsl_##shd); \
    glslSrc obj(&res_glsl_##shd[13], res_glsl_##shd##_len - 13)

class glslCommonSrc : public glslSrc {
public:
    glslCommonSrc();
    ~glslCommonSrc();
};

#endif
